<script src="views/assets/js/bootstrap.5.2.bundle.min.js"></script>
<script src="views/assets/js/jquery3.7.0.min.js"></script>
<script src="views/assets/js/script.js"></script>
<script src="views/plugins/fontawesome/fontawesome.js"></script>
<!-- <script src="views/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="views/bower_components/datatables.net-bs/js/dataTables.responsive.min.js"></script>
<script src="views/bower_components/datatables.net-bs/js/responsive.bootstrap.min.js"></script> -->
<!-- <script src="views/assets/js/datatables-simple-demo.js"></script>
<script src="views/assets/js/simple-datatable.min.js"></script> -->
<script src="views/plugins/jqueryNumber/jquerynumber.min.js"></script>
<script src="views/bower_components/moment/min/moment.min.js"></script>
<script src="views/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<script src="views/plugins/jqueryNumber/jquerynumber.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/3.0.5/daterangepicker.js"></script>
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.5.0/js/responsive.bootstrap5.min.js"></script>
